### ISSUE TITLE
effectiveness of this workaround

### ISSUE THREAD

**Issue by kostyrev** [Quentin-M/weave-tc#3]
Does this workaround suppose to eliminate the problem with dns lookup delays completely?
I've deployed it to our cluster (kops, AWS, weave) but still see 2.5 seconds delays.  
I'm testing from within ubuntu container
```
VERSION="18.04.1 LTS (Bionic Beaver)"
```
with
```
options use-vc
options single-request-reopen
```
in /etc/resolv.conf 
it's vanilla kube-dns (not CoreDNS as a backend)

I'm testing with
```
:>  /tmp/log.txt
url='ifconfig.co'
for i in `seq 1 10000`; do curl -4 -w '%{time_namelookup}\n' -o /dev/null -s $url >> /tmp/log.txt; done
sort /tmp/log.txt | uniq | tail -10
```
and get
```
0.060573
0.060597
0.060609
0.124728
0.124729
0.252937
10.522188
2.510896
2.510978
2.511511
```

**Comment by memorais** [comment]
If you are using "options use-vc" it means that your DNS queries are using TCP and not UDP. In your particular case, weave-tc will not solve any problem for you.

**Comment by Quentin-M** [comment]
weave-tc fixes the race condition to a statistically satisfying degree (<1%) for our use-cases, a value which can be measured easily. Using any DNS options as you are mentioning is completely orthogonal to this solution, and will not work with any images not leveraging glibc - thus the existence of this workaround. The DNS backend does not have any influence on the issue.

**Comment by kostyrev** [comment]
yep, silly me.  
I wasn't attentive enough to test all those workarounds separately.
I'll run tests without any dns options to see if weave-tc is well suited enough.  
Anyway I've managed to resolve the issue by deploying dnsmasq on every node.
Thanks guys!

**Comment by kostyrev** [comment]
without any options and with weave-tc workaround after 3550 requests I've got 
```
10.517181
10.518508
5.513749
```
delays and that's unfortunately not acceptable for us.  So I'll stick with dnsmasq on every node workaround for a while.

**Comment by Quentin-M** [comment]
weave-tc fixes the issue entirely if applied appropriately. there are a few variables in the script.

**Comment by kostyrev** [comment]
Let me get back to it.  
So my setup is AWS, kops, Weave 2.4.0 and stock kube-dns.
I've downloaded [yaml](https://github.com/weaveworks/weave/releases/download/v2.4.0/weave-daemonset-k8s-1.8.yaml) of weave for my kubernetes' version.
Add changes stated in this repo's README
```diff
diff -U2 ~/Downloads/weave-daemonset-k8s-1.8.yaml ~/Downloads/weave-daemonset-k8s-1.8.yaml.weave-tc.yaml 
--- /Users/kostyrev/Downloads/weave-daemonset-k8s-1.8.yaml	2018-09-13 13:13:32.000000000 +0300
+++ /Users/kostyrev/Downloads/weave-daemonset-k8s-1.8.yaml.weave-tc.yaml	2018-09-13 14:12:16.000000000 +0300
@@ -172,4 +172,13 @@
                   mountPath: /run/xtables.lock
                   readOnly: false
+            - name: weave-tc
+              image: 'qmachu/weave-tc:bd94b89'
+              securityContext:
+                privileged: true
+              volumeMounts:
+                - name: xtables-lock
+                  mountPath: /run/xtables.lock
+                - name: lib-tc
+                  mountPath: /lib/tc
           hostNetwork: true
           hostPID: true
@@ -204,4 +213,7 @@
                 path: /run/xtables.lock
                 type: FileOrCreate
+            - name: lib-tc
+              hostPath:
+                path: /usr/lib/tc
       updateStrategy:
         type: RollingUpdate
```
and deployed it via kubectl apply.
So now my weave setup is like this:
```
$ kubectl get pods -n kube-system -l name=weave-net -o custom-columns=NAME:.metadata.name,IMAGE:.spec.containers[*].image
NAME              IMAGE
weave-net-5hhp2   weaveworks/weave-kube:2.4.0,weaveworks/weave-npc:2.4.0,qmachu/weave-tc:bd94b89
weave-net-6qqrq   weaveworks/weave-kube:2.4.0,weaveworks/weave-npc:2.4.0,qmachu/weave-tc:bd94b89
weave-net-sfspk   weaveworks/weave-kube:2.4.0,weaveworks/weave-npc:2.4.0,qmachu/weave-tc:bd94b89
```
From 
```
$ kubectl describe deployment -n kube-system kube-dns
```
```
Name:                   kube-dns
Namespace:              kube-system
...
  Containers:
   dnsmasq:
    Image:       gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.10
    Ports:       53/UDP, 53/TCP
```
I've learned that DNSMASQ_PORT is a default one in Dockerfile so I need to change nothing.
After running tests as stated in my message above I  can confirm it works like a charm.
First time I've just ruined it all with options in /etc/resolv.conf 'cause I was not attentive enough.
Sorry for the noise and thanks for this clever workaround.

**Comment by kostyrev** [comment]
Let me get back to it.  
So my setup is AWS, kops, Weave 2.4.0 and stock kube-dns.
I've downloaded [yaml](https://github.com/weaveworks/weave/releases/download/v2.4.0/weave-daemonset-k8s-1.8.yaml) of weave for my kubernetes' version.
Add changes stated in this repo's README
```diff
diff -U2 ~/Downloads/weave-daemonset-k8s-1.8.yaml ~/Downloads/weave-daemonset-k8s-1.8.yaml.weave-tc.yaml 
--- /Users/kostyrev/Downloads/weave-daemonset-k8s-1.8.yaml	2018-09-13 13:13:32.000000000 +0300
+++ /Users/kostyrev/Downloads/weave-daemonset-k8s-1.8.yaml.weave-tc.yaml	2018-09-13 14:12:16.000000000 +0300
@@ -172,4 +172,13 @@
                   mountPath: /run/xtables.lock
                   readOnly: false
+            - name: weave-tc
+              image: 'qmachu/weave-tc:bd94b89'
+              securityContext:
+                privileged: true
+              volumeMounts:
+                - name: xtables-lock
+                  mountPath: /run/xtables.lock
+                - name: lib-tc
+                  mountPath: /lib/tc
           hostNetwork: true
           hostPID: true
@@ -204,4 +213,7 @@
                 path: /run/xtables.lock
                 type: FileOrCreate
+            - name: lib-tc
+              hostPath:
+                path: /usr/lib/tc
       updateStrategy:
         type: RollingUpdate
```
and deployed it via kubectl apply.
So now my weave setup is like this:
```
$ kubectl get pods -n kube-system -l name=weave-net -o custom-columns=NAME:.metadata.name,IMAGE:.spec.containers[*].image
NAME              IMAGE
weave-net-5hhp2   weaveworks/weave-kube:2.4.0,weaveworks/weave-npc:2.4.0,qmachu/weave-tc:bd94b89
weave-net-6qqrq   weaveworks/weave-kube:2.4.0,weaveworks/weave-npc:2.4.0,qmachu/weave-tc:bd94b89
weave-net-sfspk   weaveworks/weave-kube:2.4.0,weaveworks/weave-npc:2.4.0,qmachu/weave-tc:bd94b89
```
From 
```
$ kubectl describe deployment -n kube-system kube-dns
```
```
Name:                   kube-dns
Namespace:              kube-system
...
  Containers:
   dnsmasq:
    Image:       gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.10
    Ports:       53/UDP, 53/TCP
```
I've learned that DNSMASQ_PORT is a default one in Dockerfile so I need to change nothing.  
Full manifest is available [here](https://pastebin.com/raw/WWyAY1Jc)
After running tests as stated in my message above I see
```
root@bash-58fccd5d4f-f6dvg:/# sort /tmp/log.txt | uniq | tail -10
0.028912
0.029025
0.029604
0.029692
0.060678
0.060686
5.514573
5.514928
5.515060
5.515098
```
after running 847 requests.
