### ISSUE TITLE
sysctl: error: 'net.core.default_qdisc' is an unknown key

### ISSUE THREAD

**Issue by jeremygaither** [Quentin-M/weave-tc#4]
Getting the following error trying to run this on my cluster (kops, aws, kube 1.9, weave, jessie):

```
+ DNSMASQ_PORT=53
+ NET_OVERLAY_IF=weave
+ sysctl -w net.core.default_qdisc=fq_codel
sysctl: error: 'net.core.default_qdisc' is an unknown key
```

On the host node, this looks okay:

```
$ sudo sysctl -a | grep qdisc
net.core.default_qdisc = pfifo_fast
```

Any ideas @Quentin-M ?

**Comment by woodlee** [comment]
The pod spec needs to contain `hostNetwork: true`.

**Comment by Quentin-M** [comment]
Yeah, sorry, I considered this pretty obvious but should've mentioned it. Thanks for the answer!
