### ISSUE TITLE
Does /lib/tc need mount as hostPath?

### ISSUE THREAD

**Issue by axot** [Quentin-M/weave-tc#9]
In README, 

> Depending on the package, the appropriate mount may not be /lib/tc, the tc binary as well as the pareto.dist file are required.

```
$ docker run -ti --rm --entrypoint /bin/ash qmachu/weave-tc:bd94b89
/ # ls -al /usr/lib/tc/
total 112
drwxr-xr-x    2 root     root           125 Jul 22 07:56 .
drwxr-xr-x    4 root     root          4096 Jul 22 07:56 ..
-rw-r--r--    2 root     root         23077 Oct 31  2017 experimental.dist
lrwxrwxrwx    1 root     root             7 Aug 20  2018 m_ipt.so -> m_xt.so
-rwxr-xr-x    2 root     root         10024 Oct 31  2017 m_xt.so
-rw-r--r--    2 root     root         23573 Oct 31  2017 normal.dist
-rw-r--r--    2 root     root         23729 Oct 31  2017 pareto.dist
-rw-r--r--    2 root     root         23447 Oct 31  2017 paretonormal.dist
/ # ls -al /lib/tc/
ls: /lib/tc/: No such file or directory
```

Could you explain more details about how to setup `/lib/tc/`, Thank you.

**Comment by Quentin-M** [comment]
Hi,

On Debian, for instance, you'll want the [iproute2](https://packages.debian.org/jessie/iproute2) package (and thus get /usr/lib/tc). Note that you must mount the version that is installed on the container host, you _can't_ use the one available in your container.

Best Regards.

**Comment by axot** [comment]
Hi @Quentin-M , thank you for the answer. So I understand we should use host `/usr/lib/tc` instead container's now. How about `tc` command? Should I also use the host one's and mount it into container? which is located in `/sbin/tc`.

**Comment by Quentin-M** [comment]
@axot I did not use the host's tc command, don't know if it is as relevant as the library itself - but you can surely try & see!
